version: "3"

services:
  ext:
    container_name: "ext_main"
    build: ../ext
    image: ext
    environment:
      REACT_APP_PUBLIC_API: http://localhost:5000/api
      REACT_APP_IMG_URL: http://localhost:5000/imgproxy
      NODE_ENV: "development"
      VERSION: 0.0
      REACT_APP_MOD_URL: http://localhost:3001
      REACT_APP_CAPTCHA_SITE_KEY: "10000000-ffff-ffff-ffff-000000000001"
    volumes:
      - "/ext/node_modules"
      - "../ext:/ext"
    command: >
      sh -c "cd /ext &&
      yarn install &&
      npm run dev"

networks:
  default:
    name: netvyne