name: Ext Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - run: yarn install
      - run: npm run lint
      - run: NODE_ENV=staging yarn build
      # - run: npm run test -- --coverage
