on:
  push:
    branches:
      - master
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger E2E Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: E2E Build
          repo: netvyne/netvyne
          token: ${{ secrets.NETVYNE_ADMIN_GITHUB_PAT }}
